import random
import pyautogui

import mouse
import time
import keyboard
running = True
time.sleep(0)
if keyboard.read_key() == "m":
    time.sleep(1)
    running = True
    print("on")
    while(running):
        a = random.uniform(0, 1)
        b = random.uniform(0, 1)
        c = random.uniform(0, 1)
        d = random.uniform(0, 1)
        e = random.uniform(0, 1)
        f = random.uniform(0, 0.2)
        g = random.uniform(0, 0.2)
        w = random.uniform(-100, 100)
        x = random.uniform(-100, 100)
        y = random.uniform(-100, 100)
        z = random.uniform(-100, 100)

        mouse.click('left')
        time.sleep(a)
        keyboard.press("a")
        time.sleep(b)
        keyboard.release("a")
        mouse.drag(0, 0, w, x, absolute=False, duration=f)
        time.sleep(c)
        keyboard.press("d")
        time.sleep(d)
        keyboard.release("d")
        mouse.drag(0, 0, y, z, absolute=False, duration=g)
        time.sleep(e)
        mouse.click('right')
        time.sleep(5)
        mouse.click('right')
        pyautogui.moveTo(700, 450)
        mouse.click('right')
        pyautogui.moveTo(750, 450)
        mouse.click('right')
        pyautogui.moveTo(800, 450)
        mouse.click('right')
        pyautogui.moveTo(850, 450)
        mouse.click('right')
        pyautogui.moveTo(900, 450)
        mouse.click('right')
        pyautogui.moveTo(950, 450)
        mouse.click('right')
        pyautogui.moveTo(1000, 450)
        mouse.click('right')
        pyautogui.moveTo(1050, 450)
        mouse.click('right')
        pyautogui.moveTo(1100, 450)
        mouse.click('right')
        pyautogui.moveTo(1150, 450)
        mouse.click('right')
        pyautogui.moveTo(1200, 450)
        mouse.click('right')
        pyautogui.moveTo(1250, 450)
        mouse.click('right')
        pyautogui.moveTo(1300, 450)
        mouse.click('right')
        pyautogui.moveTo(1350, 450)
        mouse.click('right')
        pyautogui.moveTo(1400, 450)
        mouse.click('right')
        time.sleep(random.uniform(1,7))
